@dbType = sql


### Mostrar Clientes
GET http://localhost:7892/clientes

### Mostrar Artistas sequelize
GET http://localhost:7892/{{dbType}}/artistas/

### Crear Artista sequelize
POST https://galeria-arte-api.onrender.com/{{dbType}}/artistas
Content-Type: application/json

{
  "correo_artista": "correo@prueba.com",
  "contrasenia_artista": "constrasenia segura"
}


### Artista Login
POST http://localhost:7892/{{dbType}}/artistas/login
Content-Type: application/json

{
  "correo_artista": "correo@prueba.com",
  "contrasenia_artista": "constrasenia segura"
}

### Artista mis obras
GET http://localhost:7892/{{dbType}}/artistas/misObras/
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEwNDA4MjF9.drbXIXNS5dciKeEXaaGWJUtBkUkxmqe4F55iGHwh-Ko

### Mostrar Obras
GET http://localhost:7892/{{dbType}}/obras/

### Crear Obras
POST http://localhost:7892/nosql/obras/
Content-Type: application/json

{
  "titulo": "qqqqqqqqqqqqqqqqqq",
  "descripcion_obra": "Pintura de Pablo Picasso que representa el bombardeo de Guernica durante la Guerra Civil Espanola.",
  "estilo": "Cubismo",
  "tecnica": "Oleo sobre lienzo",
  "anio_creacion": 1937,
  "dimensiones": "349 cm x 776 cm",
  "precio": 8000000,
  "disponibilidad": 1
}



### Mostrar Imagenes
GET http://localhost:7892/{{dbType}}/obras/1/imagenes

### Agregar Imagenes a una obra
POST http://localhost:7892/{{dbType}}/obras/656024ba72188fc143de48aa/imagenes
Content-Type: application/json

{
  "ruta": "url de imagen 2"
}


### Mostrar Artistas de una obra
GET http://localhost:7892/{{dbType}}/obras/1/artistas

### Agregar Artistas a una obra
POST http://localhost:7892/{{dbType}}/obras/1/artistas/
Content-Type: application/json

{
  "idArtista": "5d11db85-40c8-4aae-b0e1-792d114c0c6c"
}

### Mostrar Obras de un artista
GET http://localhost:7892/{{dbType}}/artistas/1049b985-2a2b-42a1-ba23-e2aa476fae3b/obras

### Agregar obra a un artista
POST http://localhost:7892/{{dbType}}/artistas/6557e7396ce5b254a976ef48/obras
Content-Type: application/json

{
  "idObra": "ruta 2"
}


### Mostrar Artista, Obras e Imagenes
GET http://localhost:7892/obrasArtista

### Mostar Clientes
GET http://localhost:7892/{{dbType}}/clientes

### Agregar un cliente
POST http://localhost:7892/{{dbType}}/clientes
content-type: application/json

{
  "nombre_cliente": "nombre",
  "correo_cliente": "correo@gmail.com",
  "contrasenia_cliente": "password super segura"
}

### Login Cliente
POST http://localhost:7892/{{dbType}}/clientes/login
Content-Type: application/json

{
  "correo_cliente": "correo@gmail.com",
  "contrasenia_cliente": "password super segura"
}

### Login Cliente remoto
POST https://galeria-arte-api.onrender.com/sql/clientes/login
Content-Type: application/json

{
  "correo_cliente": "correo@gmail.com",
  "contrasenia_cliente": "password super segura"
}