@dbType = sql


### Mostrar Clientes
GET http://localhost:7892/clientes

### Mostrar Artistas sequelize
GET http://localhost:7892/{{dbType}}/artistas/655bfbfbc793c55a4db731a3

### Crear Artista sequelize
POST http://localhost:7892/{{dbType}}/artistas
Content-Type: application/json

{
  "nombre_artista": "bbbbbbbbbbbbbbbbbb",
  "correo_artista": "aaaaaaaaaaaaaaaaaaaae@example.com",
  "telefono": 987654321,
  "biografia": "Prueba de biografia.",
  "nacionalidad": "Italiano",
  "imagen": "url de imagen",
  "contrasenia_artista": "constrasenia segura"
}


### Mostrar Obras
GET http://localhost:7892/{{dbType}}/obras/655bfc6fc793c55a4db731ac

### Crear Obras
POST http://localhost:7892/{{dbType}}/obras/
Content-Type: application/json

{
  "titulo": "jyrdtkfgh,nu,",
  "descripcion_obra": "Pintura de Pablo Picasso que representa el bombardeo de Guernica durante la Guerra Civil Espanola.",
  "estilo": "Cubismo",
  "tecnica": "Oleo sobre lienzo",
  "anio_creacion": 1937,
  "dimensiones": "349 cm x 776 cm",
  "precio": 8000000,
  "disponibilidad": 1
}



### Mostrar Imagenes
GET http://localhost:7892/imagenes/1

### Mostrar Artista, Obras e Imagenes
GET http://localhost:7892/obrasArtista

### Mostar Clientes
GET http://localhost:7892/{{dbType}}/clientes

### Agregar un cliente
POST http://localhost:7892/{{dbType}}/clientes
content-type: application/json

{
  "nombre_cliente": "nombre",
  "correo_cliente": "correo@gmail.com",
  "contrasenia_cliente": "password super segura"
}

### Login Cliente
POST http://localhost:7892/{{dbType}}/clientes/login
Content-Type: application/json

{
  "nombre_cliente": "nombre",
  "correo_cliente": "correo@gmail.com",
  "contrasenia_cliente": "password super segura"
}