### Mostrar Clientes
GET https://galeria-arte-api.onrender.com/clientes

### Mostrar Artistas
GET https://galeria-arte-api.onrender.com/artistas

### Mostrar Obras
GET https://galeria-arte-api.onrender.com/obras

### Mostrar Imagenes
GET https://galeria-arte-api.onrender.com/imagenes/1

### Mostrar Artista, Obras e Imagenes
GET https://galeria-arte-api.onrender.com/obrasArtista

### Agregar un cliente
POST https://galeria-arte-api.onrender.com/clientes
content-type: application/json

{
  "nombre": "nombre",
  "correo": "correo@gmail.com",
  "contrasenia": "password super segura"
}

